module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
params:
  products:
    thumbnail:
      desktop: '416x416'
      mobile: '300x300'
      scrollsnap: '240x240'

# Default
permalinks:
  products: /products/:slug/
